site_name: SquawkBus-python
site_description: A python 3 client for SquawkBus
site_dir: docs

docs_dir: documentation

repo_name: SquawkBus/SquawkBus-python
repo_url: https://github.com/SquawkBus/SquawkBus-python
edit_uri: ""

theme:
    name: "material"
    logo: images/peach.svg
    favicon: images/favicon.ico

nav:
    - index.md
    - getting-started.md
    - ssl.md
    - authentication.md
    - message-handlers.md
    - API:
          - squawkbus: api/index.md

markdown_extensions:
    - admonition
    - codehilite:
          guess_lang: false
    - jetblack_markdown.autodoc:
          class_from_init: true
          ignore_dunder: true
          ignore_private: true
          ignore_all: false
          ignore_inherited: false
          follow_module_tree: false
          prefer_docstring: true
    - toc:
          permalink: true

extra_css:
    - css/custom.css